# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 11111111
    mvc:
      throw-exception-if-no-handler-found: true
      static-path-pattern: /statics/**


# Logger Config
logging:
  level:
    com.malone.hello: debug
